apiVersion: v1
kind: Service
metadata:
  name: location-classifier-service
spec:
  type: LoadBalancer
  selector:
    app: location-classifier
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8501